# Definición de Namespace e Identificador
moodle_namespace: "demo-moodle-containers"
moodle_prefix: "moodle"

# Configuración de Base de Datos
db_name: "moodle_db"
db_user: "moodle_user"
db_pass: "Moodle2026!"
db_root_pass: "RootMoodle2026!"

# Almacenamiento
storage_class: "gp3-csi" # Cambia por tu StorageClass en OpenShift (ej. ocs-storagecluster-ceph-rbd, etc.)
storage_db_size: "10Gi"
storage_moodle_size: "20Gi"